### FastText
- Word2Vec에서 OOV(사전에 없는 용어) 문제를 해결하기 위한 모델
- Word2Vec에서는 '강아지'와 '강아지들' 문구를 다른 단어로 생각
- FastText는 Word2Vec의 학습 방식은 비슷
    - 단어를 한글자씩 잘게 쪼개서 단어의 유사도를 생성
        - '강아지' -> '강', '아', '지', '강아', '아지', '강아지' (n-gram 방식)
        - Word2Vec과 기본적인 매개변수는 같지만 min_n, max_n 매개변수가 존재
        - subword의 최소 길이와 최대 길이를 설정
        - min_n = 1, max_n = 1 --> subword를 사용하지 않겠다 -> word2vec 같은 형태로 학습

In [74]:
from gensim.models import Word2Vec, FastText

In [75]:
# 샘플 문장 생성
sentences = [
    ['이커머스', '데이터',' 분석',' 진행'],
    ['상품', '리뷰', '기반',' 감성', '분석', '합니다'],
    ['형태소',' 단위',' 임베딩', '가능']
]

# FastText 모델에 학습
model = FastText(
    sentences=sentences,
    vector_size=50,         # 단위 벡터의 차원수
    window=3,               # 주변의 확인할 단어의 개수
    min_count=1,            # 최소 출현 회수
    sg=1,                   # skip-gram 방식으로 확률 계산
    epochs=10,              # 학습 반복 횟수
    min_n = 2,
    max_n= 6,
    seed = 42
)

In [76]:
# 특정 단어의 벡터를 확인
model.wv['이커머스']

array([-2.6006429e-03, -3.4255686e-03,  1.8030420e-03,  1.5050881e-03,
       -3.6111141e-03,  5.1002949e-04,  1.7093014e-03,  7.6781091e-04,
       -2.2457694e-03, -1.0072534e-03, -7.0754642e-04,  2.3603670e-03,
       -5.4769292e-03,  2.2931136e-03,  3.8545202e-03, -2.6643821e-03,
       -3.0270445e-03,  5.3786393e-03, -1.2376003e-03, -4.9314657e-03,
       -7.5512670e-04,  1.1105256e-03,  7.3387055e-06,  2.2791058e-03,
        6.3304324e-04,  9.1039564e-04, -2.1935625e-03, -1.1274475e-03,
        6.4613861e-03,  4.8283953e-03, -1.6449264e-04, -6.0664583e-03,
       -1.2385513e-03, -3.3582167e-03,  3.0395302e-03,  4.2600650e-03,
       -1.5043815e-03,  5.5194309e-05, -5.3960987e-04,  2.7794368e-03,
        4.8562363e-03,  5.3056180e-03, -1.9701491e-03,  2.5593217e-03,
        2.3944350e-03,  2.6933046e-04,  1.3103263e-03, -8.0591161e-04,
        1.0907981e-03, -2.5261571e-03], dtype=float32)

In [77]:
# 유사 단어를 확인
model.wv.most_similar('데이터', topn=3)

[(' 분석', 0.19772478938102722),
 ('리뷰', 0.0930536612868309),
 ('합니다', 0.06960973143577576)]

In [78]:
# 학습 내용에 없는 단어를 확인
model.wv['감정']

array([ 0.00180289,  0.00130132, -0.00161187, -0.0027384 ,  0.01019737,
        0.00174926, -0.00535935,  0.00425731,  0.00662595,  0.00430931,
        0.00023247, -0.00527854,  0.001246  , -0.00025952, -0.00014524,
       -0.00099853,  0.00415697, -0.00146209, -0.00205823, -0.00323385,
       -0.00548191, -0.00226499, -0.0022882 ,  0.00310275,  0.00181781,
        0.00493084, -0.00889087,  0.00021362,  0.00581655, -0.00993536,
       -0.00344993,  0.00061568, -0.01053878, -0.00694014, -0.00532334,
        0.00378219,  0.00140172, -0.00142863,  0.0048025 ,  0.00713731,
        0.00783159, -0.00058959, -0.00432177, -0.00677435,  0.00490174,
        0.00310044, -0.0008785 ,  0.00231184,  0.00091688,  0.00329597],
      dtype=float32)

In [79]:
# Word2Vec를 이용해서 sentences 학습하고 없는 단어 확인
model2 = Word2Vec(
    sentences= sentences,
    window=3,
    vector_size=50,
    min_count=1,
    sg=1,
    epochs=10,
    seed=42
)

In [80]:
# 학습한 내용에 없는 단어를 출력
# model2.wv['감정']
# Word2Vec은 사전에 없는 단어를 단위벡터로 확인하면 에러가 발생

- Word2Vec과 FastText와 단어간의 유사도 차이 확인

    - '강아지', '강아지들' 두개의 단어는 유사한 단어
        - word2vec은 다른 단어로 인식 -> 유사도 낮게
        - FastText는 비슷한 단어로 인식 -> 유사도 높게

In [81]:
sentences2 = [
    ['고양이', '고양이들', '귀엽다',' 동물', '반려동물'],
    ['강아지', '강아지들', '귀엽다', '동물', '반려동물'],
    ['달리다', '달리는',' 달림',' 걷다', '걷는'],
    ['빠르다',' 빠른',' 느리디', '느림'],
    ['예쁘다', '예쁨', "예쁜", '매력적이다'],
    ['컴퓨터', '컴퓨팅', '컴퓨터들', '기계']
]

# 모델학습 (word2vec, fasttext)
w2v = Word2Vec(
    sentences=sentences2,
    vector_size=100,
    window=3,
    min_count=1,
    sg=1,
    epochs=50,
    seed=42
)

ft = FastText(
    sentences=sentences2,
    vector_size=100,
    window=3,
    min_count=1,
    sg=1,
    epochs=50,
    seed=42,
    min_n=2,
    max_n=6
)

In [82]:
# word2vec의 유사도 확인
print(
    'Word2Vec 유사도', w2v.wv.similarity('강아지', '강아지들')
)
# fastText의 유사도 확인
print(
    'FastText 유사도', ft.wv.similarity('강아지', '강아지들')
)

Word2Vec 유사도 0.2053309
FastText 유사도 0.38665244


In [83]:
# 비교 대상 단어들
test_text = [
    ['강아지', '강아지들'],
    ['고양이', '고양이들'],
    ['달리다', '달리는'],
    ['예쁘다', '예쁜'],
    ['컴퓨터', '컴퓨팅'],
    ['빠르다', '느림']
]



for a, b in test_text:
    w2v_sim = float(w2v.wv.similarity(a, b))        # 유사도 데이터를 실수형 변경
    ft_sim = float(ft.wv.similarity(a, b))          # 유사도 데이터를 실수형 변경
    print(f"'{a}' - '{b}'의 유사도 : \n\t Word2Vec ({round(w2v_sim, 4)}), \t FastText ({round(ft_sim, 4)})")

'강아지' - '강아지들'의 유사도 : 
	 Word2Vec (0.2053), 	 FastText (0.3867)
'고양이' - '고양이들'의 유사도 : 
	 Word2Vec (-0.0551), 	 FastText (0.36)
'달리다' - '달리는'의 유사도 : 
	 Word2Vec (-0.1299), 	 FastText (0.2549)
'예쁘다' - '예쁜'의 유사도 : 
	 Word2Vec (-0.1116), 	 FastText (-0.1192)
'컴퓨터' - '컴퓨팅'의 유사도 : 
	 Word2Vec (0.0479), 	 FastText (0.4204)
'빠르다' - '느림'의 유사도 : 
	 Word2Vec (0.0634), 	 FastText (0.0449)


In [84]:
# 상품명을 기준으로 특정 상품을 검색 시 연관 된 상품의 목록을 확인

products = {
    'P001' : '무선 이어폰 블루투스 노이즈캔슬링 충전 충전케이스',
    'P002' : '유선 이어폰 하이파이 금도금 플러그',
    'P003' : '게이밍 마우스 RGB 경량 디자인',
    'P004' : '무선 마우스 초경량 블루투스 듀얼모드',
    'P005' : '헤드폰 노이즈캔슬링 유선'
}

# products에서 FastText 통해 학습을 시키기 위해 데이터를 추출
# 필요한 데이터는 dict형 데이터에서 vlaues가 필요
datas = products.values()
# datas를 공백을 기준으로 나눠준다.
tokens = []
for data in datas:
    tokens.append(data.split())
    
tokens

[['무선', '이어폰', '블루투스', '노이즈캔슬링', '충전', '충전케이스'],
 ['유선', '이어폰', '하이파이', '금도금', '플러그'],
 ['게이밍', '마우스', 'RGB', '경량', '디자인'],
 ['무선', '마우스', '초경량', '블루투스', '듀얼모드'],
 ['헤드폰', '노이즈캔슬링', '유선']]

In [85]:
# 토큰화 된 데이터를 이용하여 FastText에 학습
ft2 = FastText(
    sentences=tokens,
    vector_size=100,
    window=3,
    min_count=1,
    sg=1,
    epochs=10,
    min_n=3,
    max_n=6, 
    seed=42
)   # subword를 사용하는 fastText 모델을 학습

In [86]:
# 단위 벡터 확인 -> vector_size 차원의 좌표
ft2.wv['마우스']

array([-3.0613008e-03, -5.0699624e-04,  6.8394386e-04,  1.6413284e-03,
        1.0845191e-03, -6.9496491e-05, -4.1513756e-04, -7.2835077e-04,
       -4.9216446e-04, -4.6191998e-03,  2.4472128e-03,  6.1459029e-03,
       -1.5931531e-03,  1.5243503e-03,  2.9871964e-03,  4.7430429e-03,
        1.7513487e-03, -3.0780616e-03,  2.4277312e-03, -3.7102163e-04,
       -3.0170593e-03, -4.6031149e-05, -2.1044968e-03,  4.2992057e-03,
        8.0491928e-04,  5.2512053e-04, -1.1071775e-03,  2.4516806e-03,
       -1.4808171e-03,  9.9382375e-04,  9.1726295e-05, -5.9450134e-03,
       -3.2995513e-03, -1.3184162e-04, -4.6210256e-04,  3.1008567e-03,
        2.0963461e-03,  5.8242650e-04,  1.3280660e-06,  1.6814932e-03,
       -2.5565375e-03,  2.4096707e-03,  1.9690532e-03, -5.7412166e-04,
       -3.7551480e-03,  3.8195294e-03, -1.1654419e-03,  1.8541269e-03,
        2.3919567e-03, -1.6058803e-03, -6.9164054e-04,  2.5763284e-04,
       -2.5971071e-04,  1.6488401e-03, -1.7786531e-03, -9.2635507e-04,
      

In [87]:
import numpy as np

# 문장의 평균 벡터를 구하는 함수 정의
def sent_vec(token, type = None):
    vecs = []
    for w in token:
        vecs.append(ft.wv[w])
    # 해당 vecs가 존재하지 않는다면 희소행렬을 되돌려준다.
    if not vecs:
        return np.zeros(ft.vector_size)
    
    # print(np.array(vecs).shape)
    
    v = np.mean(vecs, axis=0)
    # 일반적인 문장의 평균 벡터를 구하는 식
    # 평균을 올리기 위해서는 L2 정규화 -> 벡터의 거리로 나눠준다.
    
    if type == 'L2':
        v /= (np.linalg.norm(v) + 1e-12)
        # 1e-12를 더한 이유는 0으로 나눠지는 것을 방지 하기 위함
    
    # print(v.shape)
    
    return v

In [88]:
# 토큰화 된 데이터들을 평균 벡터로 변환
item_vecs = []
for t in tokens:
    # print(sent_vec(t))
    # break
    item_vecs.append(sent_vec(t))

In [89]:
# 평균 벡터를 이용해서 코사인 유사도를 확인하기 위해서
# sklearn 코사인 유사도 함수를 로드
from sklearn.metrics.pairwise import cosine_similarity

In [96]:
idx = list(products.keys()).index('P003')
cosine_similarity(item_vecs[idx:idx+1], item_vecs)

array([[0.06438545, 0.09662522, 1.0000001 , 0.21450484, 0.09070536]],
      dtype=float32)

In [105]:
# 코사인 유사도를 이용해서 가장 근접한 상품의 이름을 출력
# 추천하는 함수를 생성
def recommand_by_text(product_id):
    # 해당 상품명의 위치 값 -> item_vecs위치를 이용하여 코사인 유사도를 생성하기 위함
    # 상품의 id값들은 products라는 dict에서 해당 id의 위치를 저장
    idx = list(products.keys()).index(product_id)
    
    # item_vecs에서 해당 인덱스의 값과 전체 vectors의 값을 비교
    # 코사인 유사도를 확인하면 하나의 문장을 유사도를 확인했기 때문에 2차원이 아닌 1차원 데이터를 생성
    sims =cosine_similarity(item_vecs[idx:idx+1], item_vecs).ravel()
    # 내림차순 정렬
    order = sims.argsort()[::-1]
    # 추천 단어들을 출력
    rec = []
    for i in order:
        # 코사인 유사도에서 같은 id라면 추천하지 않는다.
        if list(products.keys())[i] != product_id:
            # 상품의 id와 유사도의 값들을 rec에 추가
            rec.append([list(products.keys())[i], sims[i]])
            # rec.append([list(products.values())[i], sims[i]])
    return rec

In [116]:
rec_list = recommand_by_text('P001')

In [118]:
for idx, (pid, _) in enumerate(rec_list):
    # 유사도가 높은 상위 2개 상품의 이름을 확인
    print(products[pid])
    if idx==1:
        break

무선 마우스 초경량 블루투스 듀얼모드
유선 이어폰 하이파이 금도금 플러그
